-- Generated by nwg-displays on 2025-07-18 at 00:57:00. Do not edit manually.

hl.monitor({
	output = "eDP-1",
	mode = "1920x1080@60.0",
	position = "1920x0",
	scale = "1.0",
})

hl.monitor({
	output = "HDMI-A-1",
	mode = "1920x1080@100.0",
	position = "0x0",
	scale = "1.0",
})
